services:
    evgit.widget.abstract_widget:
        class: Evgit\Bundle\WidgetBundle\Widget\AbstractWidget
        abstract: true
        calls:
            - [setTwig, ['@twig']]

    evgit.widget.simple_widget:
        class: Evgit\Bundle\WidgetBundle\Widget\SimpleWidget
        parent: evgit.widget.abstract_widget
        calls:
            - [setName, ['simple']]
            - [setTemplate, ['{{content}}']]
        tags:
            - {name: widget}

    evgit.widget.models_widget:
        class: Evgit\Bundle\WidgetBundle\Widget\SimpleWidget
        parent: evgit.widget.abstract_widget
        calls:
            - [setName, ['models']]
            - [setTemplate, ['{{content}}']]
         tags:
            - {name: widget}
